dist: xenial
services:
    - xvfb
language: node_js
cache:
    directories:
        - '~/.npm'
env:
    global:
        secure: QqGhoH7nBSOGg9oAYj99fTZ/5JwWtx9OY+oy9jZknTSrTb8e8OFNoPyG9PuPJyQWpKANRRcXZJPBjMy8SsO6KvQZtA72zK/ShCDVPiivIXBjYS2q6OvzG7RzQZD0wClnLWKFYHDcCG7CBuP1A1HMJabBplcEA4jKidjGHV389J83XHFMIgMDdCDCN04ioVuhbdtFkhb6pqXA1qlaQu3MMC5MnXx2sj5yj61az23EVREmhBi8kp6cCBhCBP4pKY5XZBhWRCV6uPTaiMtB1uKaDSiiZWe61uRJdmL2Ed8k6aX7pPcIK8feZLvRoINZvPx//1jmgcUva+saMNTi6lRT/Wac1c2KtcuLA1flGeeTVDSKxjHQPakYbr8KVbvA0OlWiv1XA9Z8VAN+ytmVd+LOAPEXcVzEC5uO0ixR8BXbV2cQl7u3PNBlJJGZA+CkZSUViNDhWAZIA9DfRyjKlmrJR/3frnY/vltiDLSBhpnc/Hoy6Ugg1GXHt+aNSdWw2jidm9XmRxom17UtkjIqcqBOTQj1ZDuuHYTJPk1Z/S0Dz2XlB0qXFHfAPHjckZLFg5L1Sz90utSzhTFhEKb1ADicedfgWgEgss84+8kJqQIVzP+QHeCnPybCqIiRsr9DObvtRNY5WnyMc9vzT6gHurFgqUk//d6VZsUpdpZJjzCdjiw=
notifications:
    email: false
addons:
    chrome: stable
node_js:
    - '10'
script:
    - npm run test:prod && npm run build
before_script:
    - 'wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip'
    - 'unzip BrowserStackLocal-linux-x64.zip'
    - './BrowserStackLocal --key "$BROWSERSTACK_KEY" --folder `pwd` &'
    - 'sleep 5'
after_success:
    - npm run travis-deploy-once "npm run report-coverage"
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
      run travis-deploy-once "npm run deploy-docs"; fi
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
      run travis-deploy-once "npm run semantic-release"; fi
branches:
    except:
        - "/^v\\d+\\.\\d+\\.\\d+$/"
